# Generated by Django 4.2.4 on 2023-08-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
