# Generated by Django 4.2.4 on 2023-08-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0002_alter_product_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='CartItem',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
        migrations.AlterModelTable(
            name='ordertracking',
            table='OrderTracking',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='ProductImage',
        ),
        migrations.AlterModelTable(
            name='producttag',
            table='ProductTag',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='Subcategory',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
