# Generated by Django 4.2.4 on 2023-09-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
