# Generated by Django 4.2.4 on 2023-09-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0004_rename_is_admin_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
