# Generated by Django 4.2.4 on 2023-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0004_alter_user_date_of_birth_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='user_images/user.png', null=True, upload_to='user_images/'),
        ),
    ]
