# Generated by Django 4.2.4 on 2023-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product_images'),
        ),
    ]
