# Generated by Django 4.2.4 on 2023-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0008_orderitem_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
