# Generated by Django 4.2.4 on 2023-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0009_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('coupen_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('percent_discount', models.IntegerField()),
            ],
        ),
    ]
