# Generated by Django 4.2.4 on 2023-11-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Commerce_app', '0010_couponcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='couponcode',
            table='CouponCode',
        ),
    ]
